# Generated by Django 3.2.16 on 2022-10-30 23:12

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(null=True)),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('zip_code', models.CharField(max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='news_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_topic', models.CharField(max_length=250)),
                ('news_content', models.TextField()),
                ('date_published', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'news information table',
            },
        ),
        migrations.CreateModel(
            name='property_table',
            fields=[
                ('property_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('property_title', models.CharField(max_length=150)),
                ('property_descriptions', models.TextField()),
                ('price', models.IntegerField()),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('image_count', models.IntegerField()),
                ('no_of_rooms', models.IntegerField()),
                ('furniture_type', models.CharField(max_length=250, null=True)),
                ('number_of_residents', models.IntegerField(null=True)),
                ('kitchen_and_other_appliance', models.CharField(max_length=250, null=True)),
                ('has_master_bedroom', models.BooleanField(default=False)),
                ('dinning_seat', models.IntegerField(null=True)),
                ('no_of_car_in_parking', models.IntegerField(null=True)),
                ('no_of_guest_toilet', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'property_table',
            },
        ),
        migrations.CreateModel(
            name='user_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='user.jpg', upload_to='user_image')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user image table',
            },
        ),
        migrations.CreateModel(
            name='transaction_details',
            fields=[
                ('tanscation_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ammount_invested', models.IntegerField()),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('transaction_status', models.CharField(choices=[('F', 'Fail'), ('S', 'Success')], max_length=4)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainbow.property_table')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user details table',
            },
        ),
        migrations.CreateModel(
            name='purchase_rental_table',
            fields=[
                ('purchase_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('ammount_invested', models.IntegerField()),
                ('date_invested', models.DateTimeField(auto_now_add=True)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainbow.property_table')),
                ('property_transaction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainbow.transaction_details')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investment table',
            },
        ),
        migrations.CreateModel(
            name='property_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='property.jpg', upload_to='property_image')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rainbow.property_table')),
            ],
            options={
                'db_table': 'property image',
            },
        ),
    ]
